### ISSUE TITLE
iOS simulator build error (only the first time)

### ISSUE THREAD

**Issue by mduchev** [dkornev/TwilioVideoXamarinIOS#1]
Every time I try to run my app on a simulator, when I click the Build for the first time, the deploy crashes with this error:
[simulator_error.txt](https://github.com/dkornev/TwilioVideoXamarinIOS/files/3672010/simulator_error.txt)

The interesting part is that if I click Run again, the app deploys with no issues. So, with each change, I have to press run twice in order to deploy my app.
This happens only if I deploy on the simulator, even if I have the registrar static mtouch argument.

**Comment by dkornev** [comment]
Hi @mduchev,
Can you provide some more info about VS, Xamarin, Xcode versions you are using?
I personally don't face this issue

**Comment by mduchev** [comment]
@dkornev Sure thing.
I am using all the latest stable releases - XCode 11. Building happens on Mac with a remote access to a mac device.
Here is the VS info:
[vs_info.txt](https://github.com/dkornev/TwilioVideoXamarinIOS/files/3695922/vs_info.txt)

Unfortunately, I don't think that the versions are the problem. This is happening for the past 2-3 months now. It started after one of the updates that I had. I didn't notice it initially, but when I come to think of it now, that may be the cause. 
The interesting thing is that this doesn't seem to happen if I try it with a brand new project. I tried clearing the bin/obj folders on Windows and also the mtbs builds folder on the mac, but the issue keeps persisting.

**Comment by dkornev** [comment]
@mduchev Thanks for the info. I'll take a look later, but as I see there is a walkaround and it definitely doesn't happen to everybody, so low-priority for now

**Comment by mduchev** [comment]
@dkornev I haven't seen this issue in a long time. I think that it must have been a Xamarin problem, or after some update it got resolved. You can close it, if you want.

**Comment by dkornev** [comment]
Thanks. Closing this
