### ISSUE TITLE
Add support for Twilio Video iOS 3.0.0

### ISSUE THREAD

**Issue by 4brunu** [dkornev/TwilioVideoXamarinIOS#2]
Hey, 

First of all, thanks for this Xamarin binding for Twilio Video iOS.

Could you please update the binding to support the Twilio Video iOS 3.0.0?
https://www.twilio.com/docs/video/changelog-twilio-video-ios-version-3x#300-october-4-2019

Thanks

**Comment by dkornev** [comment]
Thanks for creating this. I'll try to put it on my schedule

**Comment by dkornev** [comment]
The binding is updated the latest version which is v3.2.2 now

**Comment by 4brunu** [comment]
Thanks 👍
