### ISSUE TITLE
Latest version doesn't build

### ISSUE THREAD

**Issue by MKGNZ** [dkornev/TwilioVideoXamarinIOS#3]
After updating to 3.2.2 I'm getting:
>C:\Program Files (x86)\Microsoft Visual Studio\2019\Enterprise\MSBuild\Xamarin\iOS\Xamarin.iOS.Common.targets(845,3): error MT5214: Native linking failed, undefined symbol: _TVIVideoOrientationIsRotated. This symbol was referenced by the managed member Twilio.Video.iOS.CFunctions.TVIVideoOrientationIsRotated. Please verify that all the necessary frameworks have been referenced and native libraries linked.
>C:\Program Files (x86)\Microsoft Visual Studio\2019\Enterprise\MSBuild\Xamarin\iOS\Xamarin.iOS.Common.targets(845,3): error MT5214: Native linking failed, undefined symbol: _TVIVideoOrientationIsValid. This symbol was referenced by the managed member Twilio.Video.iOS.CFunctions.TVIVideoOrientationIsValid. Please verify that all the necessary frameworks have been referenced and native libraries linked.
>C:\Program Files (x86)\Microsoft Visual Studio\2019\Enterprise\MSBuild\Xamarin\iOS\Xamarin.iOS.Common.targets(845,3): error MT5214: Native linking failed, undefined symbol: _TVIVideoOrientationMakeTransform. This symbol was referenced by the managed member Twilio.Video.iOS.CFunctions.TVIVideoOrientationMakeTransform. Please verify that all the necessary frameworks have been referenced and native libraries linked.

It seems _TVIVideoOrientationIsRotated, _TVIVideoOrientationIsValid and _TVIVideoOrientationMakeTransform are missing.

Please let me know if there is a workaround.

**Comment by dkornev** [comment]
I'm using VS for Mac and it seems to be working. 
Are you using a NuGet package or building the library from the source?

**Comment by MKGNZ** [comment]
I'm Using VS 2019 on PC ver. 16.5.0.
I'm just using the NuGet package. My Xamarin app was working fine with the previous version. Once I updated and made a couple of changes as the API did change (for example past tense verbs changed to Did... for example: RemoteParticipantEnabledVideoTrack -> RemoteParticipantDidEnablVideoTrack) 
Other than that no other changes.

**Comment by jtorvald** [comment]
I updated to 3.2.2 and got same errors as OP:
```
MTOUCH : error MT5214: Native linking failed, undefined symbol: _TVIVideoOrientationIsValid. This symbol was referenced by the managed member Twilio.Video.iOS.CFunctions.TVIVideoOrientationIsValid. Please verify that all the necessary frameworks have been referenced and native libraries linked.
```
I added mtouch arguments: --registrar:static --linkskip=Twilio.Video.iOS:
When I don't linkskip I get even more errors.
Also tried variations without -cxx and --linkskip. Registrar is new right? Because that I didn't have before and it worked with the previous version.

Without --linkskip=Twilio.Video.iOS I get errors like these:
```
MTOUCH : error MT5202: Native linking failed. Please review the build log.
      "_OBJC_CLASS_$_TVIAudioTrackPublication", referenced from:
          objc-class-ref in registrar.o
      "_OBJC_CLASS_$_TVILocalTrackStats", referenced from:
          objc-class-ref in registrar.o
      "_OBJC_CLASS_$_TVILocalAudioTrackPublication", referenced from:
          objc-class-ref in registrar.o

-- stripped other lines --
```

**Comment by dkornev** [comment]
@jtorvald Are you using NuGet package also? I'll take a look deeply this weekend.

**Comment by jtorvald** [comment]
@dkornev yeah sorry, forgot to mention that. NuGet indeed.

**Comment by husamdev** [comment]
Hello, I am having the same issue, I am using the NuGet package too.

**Comment by dkornev** [comment]
I still haven't taken a look at this one. But you can try to embed the project instead of using the package as a temporary solution. It's how I'm using it at least.

**Comment by husamdev** [comment]
Okay I will. Thank you!

**Comment by husamdev** [comment]
I added the project, but it kept saying TwilioVideo native linking not found, then i downloaded the one from their website, it showed the old error.

**Comment by husamdev** [comment]
The project builds successfully on real device

**Comment by husamdev** [comment]
I downloaded the NuGet package, changed Linker behavior on my project to Link All and it worked.

**Comment by dkornev** [comment]
` <MtouchLink>SdkOnly</MtouchLink>`
Works for me

**Comment by MKGNZ** [comment]
> I downloaded the NuGet package, changed Linker behavior on my project to Link All and it worked.

@husamdev Are you on PC or MAC?

**Comment by husamdev** [comment]
@MKGNZ on mac

**Comment by MKGNZ** [comment]
It seems to be happening on VS2019 on PC. I think @jtorvald is on PC also.

**Comment by jtorvald** [comment]
@MKGNZ Mac. I still need to try the project instead of nuget.

**Comment by MKGNZ** [comment]
An update: Comparing the file StructsAndEnums.cs with the previous version I noticed that the 2 methods that have issues have different attributes: [Line 40](https://github.com/dkornev/TwilioVideoXamarinIOS/blob/48d82dfce165073940e2e1ae6219049850bd155a/src/StructsAndEnums.cs#L40)  for  example the TVIVideoOrientationIsRotated  has [DllImport ("__Internal")] but it used to be [Export("TVIVideoOrientationIsRotated")] same with the TVIVideoOrientationIsValid. 
The TVIVideoOrientationMakeTransform seems to be a new one.

**Comment by dkornev** [comment]
Could you try to return it back? I'm still not sure that it's the reason.
I wonder why it's working for me

**Comment by MKGNZ** [comment]
I'll test.
If I use "Link All" then it works (but I cannot debug). The Linker optimizes it away. 
But if I use "Don't link" for debug or "SdkOnly" then this happens.

**Comment by MKGNZ** [comment]
@dkornev YES !!! By Changing the [DllImport ("__Internal")] to [Export("...")] as it was in the previous version it worked.

**Comment by dkornev** [comment]
@MKGNZ I wonder why it's working for me.
Thank you very much, I appreciate your help. You can create a pull request OR I'll fix it on the weekends (probably tomorrow)

**Comment by MKGNZ** [comment]
I cannot make sense of it either. Even if I do F12 (Got to Definition) on Twilio.Video.iOS.CFunctions I get nothing in the metadata with [Export] and without [Export] so I have no idea how even those undefined symbols are being defined. 
![image](https://user-images.githubusercontent.com/37227480/81441069-1b95f100-913f-11ea-88dc-bdb9ceea2fb3.png)

**Comment by dkornev** [comment]
Pushing a new v3.2.5 NuGet package with the fix. Please let me know if you still can reproduce.
Closing this.

**Comment by MKGNZ** [comment]
I just used the  v3.2.5 NuGet Package and it worked !!! No build errors.
