### ISSUE TITLE
TVIDataTrackOptions Name

### ISSUE THREAD

**Issue by jtorvald** [dkornev/TwilioVideoXamarinIOS#4]
Can it be that TVIDataTrackOptions is not fully binded? I miss an option to set the track name.

Twilio release log says for: 2.0.0
The name parameter has been removed from the TVILocalDataTrack trackWithOptions:name: method. Track names can now be provided in the TVIDataTrackOptions object. [ISDK-1708]
I just don't see it. I only see Name with only a getter.

**Comment by dkornev** [comment]
@jtorvald according to the Twilio docs https://twilio.github.io/twilio-video-ios/docs/latest/Classes/TVIDataTrackOptions.html#//api/name/name the name property is read-only. I personally haven't worked with the Twilio data tracks, but it seems that there is no way to set the track name there.

Have you found the solution?

**Comment by jtorvald** [comment]
@dkornev yeah, that's what ran into as well. Very strange and hard to find how it should be done. I just added a data track without setting the name. So not really solved, but I wouldn't know how to solve it either. Not a priority now so I will close this issue.
