### ISSUE TITLE
Mute audio track (PlaybackEnabled=false)

### ISSUE THREAD

**Issue by jtorvald** [dkornev/TwilioVideoXamarinIOS#7]
I'm trying to mute an audiotrack and this should be possible within the delegate so this is what I do in RemoteParticipantPublishedAudioTrackEvent:

e.publication.RemoteTrack.PlaybackEnabled = false;

Just in my case e.publication.RemoteTrack is always null. But I do hear the audio and see the publication with the track name; video-audio (that I set in the browser).

Can this be related to a binding issue?

**Comment by dkornev** [comment]
I see no reason you the RemoteTrack might be null for you. I'm just curious why you get your remote track from the publication and not using a separate audioTrack parameter (**TVIRemoteAudioTrack audioTrack**):
`[Export("didSubscribeToAudioTrack:publication:forParticipant:")]
public override void DidSubscribeToAudioTrack(TVIRemoteAudioTrack audioTrack, TVIRemoteAudioTrackPublication publication, TVIRemoteParticipant participant)`
I don't know if it helps you but still.

We personally use the track subscription API (twilio.com/docs/video/api/track-subscriptions) to mute (unpublished) audio track for all participants. I know that you want to achieve it for the current user only and if so, it's not relevant.

Anyways, I don't think that it's a binding issue.

**Comment by jtorvald** [comment]
@dkornev thanks you saved me once again. I used the wrong event to do so. 
By the way: I updated to the newest nuget package for iOS and that is working fine now. Thanks!
