### ISSUE TITLE
TVICameraCapturer Not found and  not able to set Source to Front camera [Question ].

### ISSUE THREAD

**Issue by pranavtiw** [dkornev/TwilioVideoXamarinIOS#8]
camera = new TVICameraCapturer(TVICameraCaptureSource.FrontCamera);

localVideoTrack = TVILocalVideoTrack.TrackWithCapturer(capturer:camera,enabled:true,constraints:null,name:null);

This is the way i have done it in previous version .

**Comment by dkornev** [comment]
`// Create a video track which captures from the camera.

                if (LocalVideoTrack == null)
                {
                    if (ObjCRuntime.Runtime.Arch != ObjCRuntime.Arch.DEVICE) return false;

                    var frontCamera = TVICameraSource.CaptureDeviceForPosition(AVCaptureDevicePosition.Front);
                    var backCamera = TVICameraSource.CaptureDeviceForPosition(AVCaptureDevicePosition.Back);

                    if (frontCamera != null || backCamera != null)
                    {
                        // Preview our local camera track in the local video preview view.
                        _camera = new TVICameraSource(_cameraSourceDelegate);
                        if (_camera == null) return false;

                        LocalVideoTrack = TVILocalVideoTrack.TrackWithSource(_camera, true, "Camera");
                        if (LocalVideoTrack != null)
                        {
                            // Add renderer to video track for local preview
                            foreach (var videoView in VideoViews)
                            {
                                LocalVideoTrack.AddRenderer(videoView.VideoView);
                            }

                            LogHelper.Info("Video track created");
                        }

                        bool result;
                        if (frontCamera != null && backCamera != null)
                        {
                            result = true;
                        }
                        else
                        {
                            result = false;
                        }

                        _camera?.StartCaptureWithDevice(frontCamera ?? backCamera,
                            (captureDevice, videoFormat, error) =>
                            {
                                if (error != null)
                                {
                                    LogHelper.Info($"Capture failed with error.code = {error?.Code} error = {error?.Description}");
                                }
                                else
                                {
                                    MirrorMode = captureDevice?.Position == AVCaptureDevicePosition.Front;
                                }
                            });

                        return result;
                    }
                    else
                    {
                        LogHelper.Info($"No front or back capture device found!");
                        return false;
                    }
                }
                return true;`

@pranavtiw That is how I'm doing it.
Let me know if it helps

**Comment by pranavtiw** [comment]
Thanks aloot ...

**Comment by dkornev** [comment]
Can I close this?

**Comment by pranavtiw** [comment]
Sure .
But just a request ...it would be great if you can attach a sample .. like
how we connect to room and show the remote participant view
